### ISSUE TITLE
容器配置（非WEBUI）修改密码后，登录时有概率报账号或密码错误

### ISSUE THREAD

**Issue by leic4u** [devome/dockerfiles#145]
原密码：Dk5LjB63X8Tde#c$WY
新密码：Dk5LjB63X8Tde

群晖 container 部署，因群晖支持 compose 了，就把容器转为通过 compose 启动了。其他配置参数和非 compose 部署时没有变化，仅修改了密码。修改密码是因为 .yaml 中的 `#` 和密码中的 `#` 冲突了，图方便就直接删掉了井号以及后面的字符，只留了前面13位的大写+小写+数字密码。

但通过compose 启动容器后，会出现新旧密码都登录不上去的情况，但是隔一会儿尝试又有几率用新密码登上去。神奇。

出现两次了，两次都是在我试密码试了半天之后，想去群晖 container 重启 qb 容器时，打开看了下配置，但还没重启，再试就可以登录了。难道 qb 有自主意识怕我重启它吗？😂[手动狗头]

确定账号密码没有输错，因为我是通过 bitwarden 浏览器插件，自动填充的账号密码，不是手输的。

compose 配置如下：
```yaml
services:
  qbittorrent:
    image: nevinee/qbittorrent  # 如想参与测试工作可以指定nevinee/qbittorrent:unstable，如想使用集成了iyuu的版本请指定nevinee/qbittorrent:iyuu
    container_name: qbittorrent
    restart: always
    tty: true
    network_mode: host
    hostname: NAS-qbitorrent
    stop_grace_period: 10m # 让qBittorrent程序自行退出后再关闭/删除/重启容器的最长时间，如不设置，则docker默认10秒，这时，种子多的qBittorrent可能还没有完全保存好全部需要保存的信息。
    volumes:
      - ./:/data      # 配置保存目录
      - ./config/auto-cat:/usr/local/bin/auto-cat
      - /volume2/other:/other
      - /volume2/video:/video
      - /volume1/music:/music
      - /volume1/movie:/movie
    tmpfs:
      - /tmp
    environment:          # 下面未列出的其他环境变量请根据环境变量清单自行添加
      - WEBUI_PORT=8080   # WEBUI控制端口，可自定义
      - BT_PORT=55555     # BT监听端口，可自定义
      - PUID=0         # 输入id -u可查询，群晖必须改
      - PGID=0          # 输入id -g可查询，群晖必须改
      - TZ=Asia/Shanghai
      - QB_USERNAME=qbqbqb-admin
      - QB_PASSWORD=Dk5LjB63X8Tde
      - DL_FINISH_NOTIFY=true
      - TG_API_HOST=tg.abc.com
      - TG_USER_ID=7777777777
      - TG_BOT_TOKEN=11111111111111:AAAAAAAAAAAAAAAAAAAAAAAAAAA
      - WORK_WECHAT_BOT_KEY=3333333-6666-4444-9999-66666666666666
      - CRON_HEALTH_CHECK=12 * * * *
      - TRACKER_ERROR_COUNT_MIN=3
      - ENABLE_AUTO_CATEGORY=true
      - ENABLE_AUTO_CATEGORY=category
      - CRON_AUTO_CATEGORY=*/2 * * * *
      - CRON_TRACKER_ERROR=52 * * * *
      - CRON_IYUU_HELP=*/5 * * * *
        #ports:
        #- 8087:8087        # 冒号左右一致，必须同WEBUI_PORT一样，本文件中的3个8080要改一起改
        #- 34567:34567      # 冒号左右一致，必须同BT_PORT一样，本文件中的5个34567要改一起改
        #- 34567:34567/udp  # 冒号左右一致，必须同BT_PORT一样，本文件中的5个34567要改一起改
      #- 8787:8787       # 如使用的是nevinee/qbittorrent:iyuu标签，请解除本行注释
    #security_opt:       # armv7设备请解除本行和下一行的注释
      #- seccomp=unconfined
```

容器日志没有显示登录问题。

![Image](https://github.com/user-attachments/assets/92b1748c-3b0b-42af-a7a7-48c283cf69ec)
